# Generated by Django 6.0.8 on 2026-08-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_foodlog_created_at_exerciselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (Little or no exercise)'), ('light', 'Lightly Active (Exercise 1-3 days/week)'), ('moderate', 'Moderately Active (Exercise 3-5 days/week)'), ('active', 'Very Active (Exercise 6-7 days/week)'), ('extra_active', 'Extra Active (Hard exercise / physical job)')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_calorie_burn_target',
            field=models.PositiveIntegerField(default=0, help_text='Custom Daily Active Calorie Burn Goal (kcal)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_calorie_target',
            field=models.PositiveIntegerField(default=0, help_text='Custom Daily Calorie Target (kcal)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_protein_target',
            field=models.FloatField(default=0.0, help_text='Custom Daily Protein Goal (g)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss / Fat Burn'), ('maintenance', 'Maintain Weight & Fitness'), ('muscle_gain', 'Muscle Gain / Build Strength')], default='weight_loss', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
